
--GET NOMINAS POR PERSONA ID 
SELECT * 
FROM NOMINA_PERSONA
WHERE NOP_FK_PERSONA_ID = 828146
ORDER BY NOP_FECHA


SELECT * 
FROM NOMINA_PERSONA
INNER JOIN PERSONA
ON NOMINA_PERSONA.NOP_FK_PERSONA_ID = PERSONA.PER_ID
WHERE PERSONA.PER_ID = 828146
ORDER BY NOP_FECHA


--CAMBIAR ESTADO VISIBILIDAD A VISIBLE
BEGIN TRANSACTION

UPDATE NOMINA_PERSONA
SET NOP_ESTADO = 1
WHERE NOP_ID = 717825

ROLLBACK
COMMIT


SELECT   NOP_FECHA,   NOP_ID,   NOP_TIPO,   NOP_FILE_NAME,   PER_NOMBRE,   PER_APELLIDOS,   PER_NIF,   PER_NUMERO_EMPLEADO,   
         EDP_NOMBRE,   RAZ_NOMBRE,   CTR_NOMBRE,   PER_ID,   ISNULL(NOP_ESTADO, 0) AS NOP_ESTADO,   ROW_NUMBER() OVER(ORDER BY NOP_FECHA DESC, 
		 PER_APELLIDOS, PER_NOMBRE DESC) as ROW_NUM  
FROM     NOMINA_PERSONA 
			INNER JOIN  PERSONA ON NOMINA_PERSONA.NOP_FK_PERSONA_ID = PERSONA.PER_ID 
			LEFT OUTER JOIN   EMPRESA_DEPARTAMENTO ON PERSONA.PER_FK_DEPARTAMENTO = EMPRESA_DEPARTAMENTO.EDP_ID 
			INNER JOIN   RAZON_SOCIAL ON PERSONA.PER_FK_RAZON_SOCIAL_ID = RAZON_SOCIAL.RAZ_ID 
			LEFT OUTER JOIN   CENTRO_TRABAJO ON PERSONA.PER_FK_CENTRO_TRABAJO_ID = CENTRO_TRABAJO.CTR_ID 
WHERE   PER_FK_EMPRESA_ID=13169 AND 
		--PER_NOMBRE = 'JULIA'
		PER_NUMERO_EMPLEADO = '02627'
ORDER BY NOP_FECHA


  SELECT TOP (1000) [PER_ID]
      ,[PER_NIF]
	  ,[PER_FK_EMPRESA_ID]
      ,[PER_USUARIO_REAL]
      ,[PER_ALTA_SISTEMA]
      ,[PER_BAJA_SISTEMA]
      ,[PER_NOMBRE]
	  ,PER_FK_PAIS_ASIGNACION

  FROM PlataformaPRE.[dbo].[PERSONA]
  WHERE [PER_FK_EMPRESA_ID] = 13169
  AND PER_FK_PAIS_ASIGNACION IS NULL

SELECT TOP (1000) [PER_ID]
      ,[PER_NIF]
	  ,[PER_FK_EMPRESA_ID]
      ,[PER_USUARIO_REAL]
      ,[PER_ALTA_SISTEMA]
      ,[PER_BAJA_SISTEMA]
      ,[PER_NOMBRE]
	  ,PER_FK_PAIS_ASIGNACION

  FROM PlataformaPRE.[dbo].[PERSONA]
  WHERE PER_FK_PAIS_ASIGNACION IS NULL


BEGIN TRANSACTION

	UPDATE PERSONA
	SET PER_FK_PAIS_ASIGNACION = 73
	WHERE  PER_NIF IN  ('39395197S', 'DEMODENSOAPP' )

  ROLLBACK
COMMIT