SELECT 
PRE_ID AS 'PeticionReservaId'
, ADH_ID AS 'AhesionGenericoId'
, PER_ID as 'PersonaId'
, PER_NIF AS 'Nif'
, PER_NUMERO_EMPLEADO AS 'NumEmpleado'
, PER_NOMBRE AS 'Nombre'
, PER_APELLIDOS AS 'Apellidos'
, PER_EMAIL AS 'Email'
, CTR_ID AS 'CentroTrabajoId'
, CTR_NOMBRE AS 'CentroTrabajoNombre'
, RAZ_ID AS 'RazonSocialId'
, RAZ_NOMBRE AS 'RazonSocialNombre'
, OFE_NOMBRE AS 'OfertaNombre'
, ISNULL(PRE_FECHA, ISNULL(ADH_FECHA_PETICION, ADH_FECHA_CONTRATACION)) As 'FechaSolicitada'
, ISNULL(PRE_FECHA_RESERVA, ADH_FECHA_CONTRATACION) as 'FechaSolicitud'
, ISNULL(PRE_FECHA_ULTIMA_MODIFICACION, ADH_FECHA_ULTIMA_MODIFICACION) as 'FechaUltimaModificacion'
, ADH_ESTADO as 'Estado'
, PCA_ULTIMO_NIVEL.PCA_DESCRIPCION As 'UltimoNivelDescripcion'
, PCU_DESC As 'UnidadDescripcion'
, PCU_ID As 'UnidadDescripcionId'
, ADH_SUB_ESTADO AS 'SubEstado'
, ADH_MOTIVO_CAMBIO_ESTADO AS 'MotivoEstado'
FROM ADHESION_GENERICO
INNER JOIN PERSONA_PLAN
	ON PPL_ID = ADH_PPL_ID
INNER JOIN EMPRESA_PLAN
	ON PLA_ID = PPL_FK_EMPRESA_PLAN_ID
INNER JOIN PERSONA
	ON PER_ID = PPL_FK_PERSONA_ID
INNER JOIN OFERTA_ITEM
	ON OFE_ID = ADH_FK_OFERTA_ITEM_ID
LEFT JOIN PETICION_RESERVA
	ON PRE_FK_ADHESION_GENERICO_ID = ADH_ID
LEFT JOIN PETICION_TURNO_FECHAS
	ON PTF_ID = PRE_FK_PETICION_TURNO_FECHAS_ID 
LEFT JOIN PETICION_CAPACIDADES PCA_PRIMER_NIVEL
	ON PCA_PRIMER_NIVEL.PCA_ID = PTF_FK_PETICION_CAPACIDADES_ID
	LEFT JOIN PETICION_PROCESO
ON PCA_PRIMER_NIVEL.PCA_FK_PETICION_PROCESO_ID = PPR_ID
LEFT JOIN CENTRO_TRABAJO
	ON CTR_ID = ISNULL(PCA_PRIMER_NIVEL.PCA_FK_CENTRO_TRABAJO_ID, PER_FK_CENTRO_TRABAJO_ID)
LEFT JOIN RAZON_SOCIAL
	ON RAZ_ID = PER_FK_RAZON_SOCIAL_ID
LEFT JOIN PETICION_CAPACIDADES_UNIDADES
	ON PRE_FK_PETICION_CAPACIDADES_UNIDADES_ID = PCU_ID
LEFT JOIN PETICION_CAPACIDADES PCA_ULTIMO_NIVEL
	ON PCA_ULTIMO_NIVEL.PCA_ID = ISNULL(PRE_FK_PETICION_CAPACIDADES_ULTIMO_NIVEL_ID,PER_FK_PETICION_CAPACIDAD_ID)

 WHERE 0 = 0 
 AND PLA_FK_EMPRESA_ID = 38
 AND PER_USUARIO_REAL = 1
 AND (PPR_FK_PETICION_TIPO_PROCESO IS NULL OR PPR_FK_PETICION_TIPO_PROCESO = 2)
 AND CONVERT(DATE, ISNULL(PRE_FECHA, ISNULL(ADH_FECHA_PETICION, ADH_FECHA_CONTRATACION))) >= CONVERT(DATE, '2021-07-01')
 AND CONVERT(DATE, ISNULL(PRE_FECHA, ISNULL(ADH_FECHA_PETICION, ADH_FECHA_CONTRATACION))) <= CONVERT(DATE, '2021-09-11')
 AND OFE_COD_INTERFACE IN ('RESTAURANT')
