SELECT*
FROM GRUPO_APARIENCIA

SELECT GAP_FORZAR_FIRMA_CAMBIO_SDAD
FROM GRUPO_APARIENCIA

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME = 'GAP_FORZAR_FIRMA_CAMBIO_SDAD'


--ADD GAP_FORZAR_FIRMA_CAMBIO_SDAD TO GRUPO_APARIENCIA EN LOCALSUEZ

BEGIN TRAN

ALTER TABLE [dbo].[GRUPO_APARIENCIA]
ADD GAP_FORZAR_FIRMA_CAMBIO_SDAD BIT NULL 

ROLLBACK
COMMIT
