SELECT 
OFE_ID,
OFE_COD_INTERFACE,
ADH_ESTADO, 
*
FROM 
PERSONA_PLAN
INNER JOIN OFERTA_ITEM
	ON OFE_FK_EMPRESA_PLAN_ID = PPL_FK_EMPRESA_PLAN_ID
INNER JOIN ADHESION_GENERICO
	ON ADH_FK_OFERTA_ITEM_ID = OFE_ID
	WHERE PPL_ID = 3016541
	AND ADH_ADHESION = 1
	AND ADH_ESTADO = 2
	AND OFE_COD_INTERFACE = 'TELETRA'