--COSULTA PARA SABER TRABAJADORES DE UN MANAGER

SELECT * FROM  JERARQUIA_APROBACION_PRODUCTOS_RELACION


SELECT DISTINCT JAPR_FK_PER_ID_COLABORADOR FROM  JERARQUIA_APROBACION_PRODUCTOS_RELACION
WHERE JAPR_FK_PER_ID_JEFE = 605121


SELECT JAPR_FK_PER_ID_COLABORADOR 
FROM  JERARQUIA_APROBACION_PRODUCTOS_RELACION
WHERE JAPR_FK_PER_ID_JEFE = 619934
