
-- LEN CON VARCHAR OBTIENE EL Nº DE CARACTERES SIN LOS ESPACIOS EN BLANCO
SELECT
    OFE_COD_INTERFACE,
	OFE_FK_EMPRESA_PLAN_ID,
    LEN(OFE_COD_INTERFACE) len
FROM
    OFERTA_ITEM
WHERE OFE_COD_INTERFACE IS NOT NULL


-- DATALENGTH CON VARCHAR OBTIENE EL Nº DE CARACTERES SUMANDO LOS ESPACIOS EN BLANCO
SELECT
    OFE_COD_INTERFACE,
	OFE_FK_EMPRESA_PLAN_ID,
    DATALENGTH(OFE_COD_INTERFACE) data_length
FROM
    OFERTA_ITEM
WHERE OFE_COD_INTERFACE IS NOT NULL
