
SELECT JAPR_ID, PJ.PER_NIF AS NIF_JEFE, PC.PER_NIF AS NIF_COLABORADOR, JAPR_FK_JAP_ID AS Jerarquia
FROM JERARQUIA_APROBACION_PRODUCTOS_RELACION
INNER JOIN PERSONA PJ ON JAPR_FK_PER_ID_JEFE = PJ.PER_ID
INNER JOIN PERSONA PC ON JAPR_FK_PER_ID_COLABORADOR = PC.PER_ID
WHERE PJ.PER_FK_EMPRESA_ID = 2533 AND PC.PER_FK_EMPRESA_ID = 2533 AND JAPR_FK_JAP_ID = 33

BEGIN TRANSACTION

--Borrado de jerarquías con tipo (33 = Registro Horario) que no corresponde en Amex 
DELETE FROM [dbo].[JERARQUIA_APROBACION_PRODUCTOS_RELACION]
      WHERE JAPR_ID IN (50817,50818,50819,50820,50821,50822,50823) 
GO

ROLLBACK
COMMIT
