SELECT *
FROM PETICION_CAPACIDADES

SELECT *
FROM PETICION_CAPACIDADES_UNIDADES
 
SELECT *
FROM PETICION_PROCESO

SELECT * 
FROM PETICION_TIPO_PROCESO

SELECT *
FROM PETICION_RESERVA

SELECT * 
FROM EMPRESA WHERE EMP_ID = 632 --BMW

SELECT * 
FROM EMPRESA WHERE EMP_ID = 38 --SUEZ

SELECT *
FROM CENTRO_TRABAJO
WHERE CTR_FK_EMPRESA_ID = 38


--GENÉRICA
SELECT 
  PCU_DESC As 'UnidadDescripcion'
, PCU_ID As 'UnidadDescripcionId'
FROM PETICION_PROCESO
INNER JOIN PETICION_CAPACIDADES
    ON PPR_ID = PCA_FK_PETICION_PROCESO_ID
INNER JOIN PETICION_CAPACIDADES_UNIDADES
    ON PCU_FK_PETICION_CAPACIDAD_ID = PCA_ID
INNER JOIN PETICION_TIPO_PROCESO
    ON PPR_FK_PETICION_TIPO_PROCESO = PTP_ID


--BMW
SELECT DISTINCT PCU_DESC, PCU_ID, PCA_DESCRIPCION
FROM PETICION_PROCESO
INNER JOIN PETICION_CAPACIDADES
    ON PPR_ID = PCA_FK_PETICION_PROCESO_ID
INNER JOIN PETICION_CAPACIDADES_UNIDADES
    ON PCU_FK_PETICION_CAPACIDAD_ID = PCA_ID
INNER JOIN PETICION_TIPO_PROCESO
    ON PPR_FK_PETICION_TIPO_PROCESO = PTP_ID
WHERE PPR_FK_EMPRESA_ID = 632  
AND PPR_FK_PETICION_TIPO_PROCESO = 1


--SUEZ
SELECT *
FROM PETICION_PROCESO
INNER JOIN PETICION_CAPACIDADES
    ON PPR_ID = PCA_FK_PETICION_PROCESO_ID 
INNER JOIN PETICION_CAPACIDADES_UNIDADES
    ON PCU_FK_PETICION_CAPACIDAD_ID = PCA_ID
INNER JOIN PETICION_TIPO_PROCESO
    ON PPR_FK_PETICION_TIPO_PROCESO = PTP_ID
WHERE PPR_FK_EMPRESA_ID = 38 
AND PPR_FK_PETICION_TIPO_PROCESO = 2




