--ADD BIT AND VARCHAR TO RH CONFIGURATION

SELECT *
FROM LocalRegHorario.dbo.RH_CONFIGURACION


BEGIN TRAN

ALTER TABLE [LocalRegHorario].[dbo].[RH_CONFIGURACION]
ADD RHC_ACTIVAR_TT_OFERTA_APROBACION BIT NOT NULL DEFAULT (0)

ALTER TABLE [LocalRegHorario].[dbo].[RH_CONFIGURACION]
ADD RHC_CODIGO_IFAZ_OFERTA VARCHAR(100) NULL

ROLLBACK
COMMIT



