
--GET EMPLEADOS DEMOS Y REALES DE UNA EMPRESA
SELECT *
FROM LocalFlex.dbo.PERSONA
WHERE PER_FK_EMPRESA_ID = 12881

--GET EMPLEADOS REALES DE UNA EMPRESA
SELECT *
FROM LocalFlex.dbo.PERSONA
WHERE PER_FK_EMPRESA_ID = 12881
AND PER_USUARIO_REAL = 1

--GET NUMERO DE EMPLEADOS DE UNA EMPRESA
SELECT COUNT(*)
FROM LocalFlex.dbo.PERSONA
WHERE PER_FK_EMPRESA_ID = 12881
AND PER_USUARIO_REAL = 1