
--EMPRESA HORA CORTE Y HORA NOTIFICACION

SELECT 
EMP_ID
,EMP_NOMBRE
,PPR_HORA_CORTE_SOLICITUD
,PPR_NOTIFICACION_CENTRO_TRABAJO_HORA
FROM EMPRESA
INNER JOIN [PETICION_PROCESO]
ON EMP_ID = PPR_FK_EMPRESA_ID
WHERE EMP_ID IN('13183','28','12881','2422','2584','1410','632')





