SELECT * FROM RV_OBJETIVO_INTEGRACION


BEGIN TRAN

ALTER TABLE [dbo].[RV_OBJETIVO_INTEGRACION]
--ADD RV_OI_FK_PERSONA_ID NUMERIC(18, 0)
ADD FOREIGN KEY (RV_OI_FK_PERSONA_IDO) REFERENCES [dbo].[PERSONA] (PER_ID)

ROLLBACK
COMMIT



/*

BEGIN TRAN

ALTER TABLE [dbo].[PERSONA]
ADD PER_ESTADO_ACEPTACION_RGPD BIT NOT NULL DEFAULT (0)

ROLLBACK
COMMIT
*/