--ADD COLUMN TO TABLE

--SCHEMA--
--ALTER TABLE table_name
--ADD column_name datatype;


BEGIN TRAN

ALTER TABLE [dbo].[GRUPO_APARIENCIA]
ADD GAP_FORZAR_FIRMA_CAMBIO_SDAD BIT NULL 

ROLLBACK
COMMIT