--GET NUMBERS OF TABLES FROM DATABASE

USE LocalRegHorario --Insert database name
SELECT COUNT(*) AS 'NUMBER OF TABLES' 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'

USE LocalSuez --Insert database name
SELECT COUNT(*) AS 'NUMBER OF TABLES' 
FROM sys.tables