
--OBTENGO REGISTRO HORARIO PERSONA ID PARTIR DE PPL_ID
SELECT RHP_ID
FROM LocalRegHorario.dbo.RH_PERSONA
WHERE RHP_FK_PERSONA_ID IN (
	SELECT PPL_FK_PERSONA_ID
	FROM localFlex.dbo.PERSONA_PLAN
	WHERE PPL_ID = 3077741 )
AND RHP_FK_RH_CONEXION_ID = 1


--OBTENGO TODOS LOS REGISTROS DE RH RH_PERSONA_ID QUE CUMPLEN FECHA Y REGULARIZACIÓN
SELECT RHF_ID
FROM LocalRegHorario.dbo.RH_FINALIZADOS
WHERE RHF_FK_RH_PERSONA_ID = 64831
AND RHF_MOTIVO_REGULARIZACION = 'Regularización a 0'
AND RHF_FECHA_HORA_INICIO = '2022-11-01'
