SELECT *
FROM localFlex.dbo.EMPRESA
WHERE EMP_NOMBRE = 'Cuatrecasas'
ORDER BY EMP_NOMBRE

SELECT *
FROM LocalRegHorario.dbo.RH_TIPO_DIA
WHERE RHTD_FK_EMPRESA_ID = 632 --413
ORDER BY RHTD_NOMBRE

BEGIN TRANSACTION

DELETE FROM 
LocalRegHorario.dbo.RH_TIPO_DIA
WHERE RHTD_ID IN(1310)
AND RHTD_FK_EMPRESA_ID = 632

ROLLBACK
COMMIT

