

SELECT PER_FK_PETICION_CAPACIDAD_ID_4 
FROM PERSONA

-- AÑADIR PER_FK_PETICION_CAPACIDAD_ID_4 (OTROS) A PERSONA
BEGIN TRAN

ALTER TABLE [dbo].[PERSONA]
ADD PER_FK_PETICION_CAPACIDAD_ID_4 INT 

ROLLBACK
COMMIT

BEGIN TRAN

ALTER TABLE [dbo].[PERSONA]  WITH NOCHECK ADD CONSTRAINT [FK_PERSONA_PETICION_CAPACIDAD_4] FOREIGN KEY([PER_FK_PETICION_CAPACIDAD_ID_4])
REFERENCES [dbo].[PETICION_CAPACIDADES] ([PCA_ID])

ROLLBACK
COMMIT