--JORNADAS DUPLICADAS PARA UNA EMPRESA EN LA QUE LA JORNADA DUPLICADA SEA DIFERENTE DE VACACIONES
SELECT RHP_ID
, RHJL_MIN.RHJL_ID
, RHJL_MIN.RHJL_FECHA_HORA_INICIO
, RHJL_MIN.RHJL_FECHA_CARGA
, RHTD_MIN.RHTD_NOMBRE
, RHJL_REP.RHJL_ID AS  'RHJL_ID Jornada a eliminar'
, RHJL_REP.RHJL_FECHA_HORA_INICIO
, RHJL_REP.RHJL_FECHA_CARGA
, RHTD_REP.RHTD_NOMBRE
, RHTD_REP.RHTD_ID
    FROM PERSONA
    INNER JOIN [RegHorarioPRE].dbo.RH_PERSONA
        ON RHP_FK_PERSONA_ID = PER_ID AND RHP_FK_RH_CONEXION_ID = 1
    INNER JOIN  [RegHorarioPRE].dbo.RH_JORNADA_LABORAL RHJL_MIN
        ON RHJL_MIN.RHJL_FK_RH_PERSONA_ID = RHP_ID
        AND RHJL_MIN.RHJL_FK_RH_TIPO_DIA_ID = 340
    INNER JOIN  [RegHorarioPRE].dbo.RH_JORNADA_LABORAL RHJL_REP
        ON RHJL_REP.RHJL_FK_RH_PERSONA_ID = RHP_ID
        AND CONVERT(DATE, RHJL_REP.RHJL_FECHA_HORA_INICIO) = CONVERT(DATE, RHJL_MIN.RHJL_FECHA_HORA_INICIO)
        AND RHJL_REP.RHJL_ID <> RHJL_MIN.RHJL_ID
    LEFT JOIN [RegHorarioPRE].dbo.RH_TIPO_DIA RHTD_MIN
        ON RHTD_MIN.RHTD_ID = RHJL_MIN.RHJL_FK_RH_TIPO_DIA_ID
    LEFT JOIN [RegHorarioPRE].dbo.RH_TIPO_DIA RHTD_REP
        ON RHTD_REP.RHTD_ID = RHJL_REP.RHJL_FK_RH_TIPO_DIA_ID
    WHERE  RHP_FK_RH_CONEXION_ID = 1
    AND CONVERT(DATE, RHJL_MIN.RHJL_FECHA_HORA_INICIO) >= CONVERT(DATE,'2022-01-01')
    AND PER_FK_EMPRESA_ID = 2533
    AND PER_BAJA_SISTEMA IS NULL


