SELECT
PERSONA.PER_NIF AS 'NIF'
, PERSONA.PER_NOMBRE AS 'Nombre'
, PERSONA.PER_APELLIDOS AS 'Apellidos'
,   EDP_NOMBRE As 'Departamento'
, PERSONA_JEFE.PER_NOMBRE AS 'Nombre Manager' 
, PERSONA_JEFE.PER_APELLIDOS AS 'Apellidos Manager' 
,  COL.COL_NOMBRE AS 'Colectivo'
, CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,103) AS 'Fecha Registro'
, ISNULL(CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,24),'No informado') AS 'Hora inicio (Finalizado)'
, ISNULL(CONVERT(VARCHAR,RHF_FECHA_HORA_FIN,24),'No informado') AS 'Hora fin (Finalizado)'
,   [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHF_TIEMPO_EFECTIVO, 's')  AS 'Tiempo efectivo (Finalizado)'
,   [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHF_TIEMPO_PAUSA, 's')  AS 'Tiempo de pausa (Finalizado)'
, ISNULL(CONVERT(VARCHAR,RHJL_FECHA_HORA_INICIO,24),'No informado') AS 'Hora inicio (Teórico)'
, ISNULL(CONVERT(VARCHAR,RHJL_FECHA_HORA_FIN,24),'No informado') AS 'Hora fin (Teórico)'
,   [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHJL_TIEMPO_EFECTIVO, 's')  AS 'Tiempo efectivo (Teórico)'
,   [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHJL_TIEMPO_PAUSA, 's')  AS 'Tiempo de pausa (Teórico)'
, 
CASE 
	WHEN (RHJL_TIEMPO_EFECTIVO - RHF_TIEMPO_EFECTIVO) < 0 
		THEN [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS( RHF_TIEMPO_EFECTIVO - RHJL_TIEMPO_EFECTIVO, 's')
	WHEN (RHJL_TIEMPO_EFECTIVO - RHF_TIEMPO_EFECTIVO) > 0 
		THEN '- ' + [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHJL_TIEMPO_EFECTIVO - RHF_TIEMPO_EFECTIVO, 's')
	ELSE [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHJL_TIEMPO_EFECTIVO - RHF_TIEMPO_EFECTIVO, 's')
END AS 'Tiempo extra generado'
,
CASE ISNULL(RHF_ESTADO, 2)
	WHEN 1 THEN 'Pendiente'
	WHEN 2 THEN 'Aceptado'
	WHEN 3 THEN 'Denegado'
	WHEN 4 THEN 'Rechazado'
	END AS 'Estado'
FROM [LocalRegHorario].[dbo].[RH_PERSONA]
INNER JOIN PERSONA ON PER_ID = RHP_FK_PERSONA_ID
AND RHP_FK_RH_CONEXION_ID = 1
LEFT JOIN EMPRESA_DEPARTAMENTO ON PER_FK_DEPARTAMENTO = EDP_ID
INNER JOIN [LocalRegHorario].[dbo].[RH_FINALIZADOS] ON RHF_FK_RH_PERSONA_ID = RHP_ID
LEFT JOIN [LocalRegHorario].[dbo].[RH_JORNADA_LABORAL] ON RHF_FK_RH_PERSONA_ID = RHJL_FK_RH_PERSONA_ID AND CONVERT(date, RHJL_FECHA_HORA_INICIO) = CONVERT(date, RHF_FECHA_HORA_INICIO)
LEFT JOIN JERARQUIA_APROBACION_PRODUCTOS_RELACION ON PER_ID = JAPR_FK_PER_ID_COLABORADOR AND JAPR_FK_JAP_ID = 56 --Id de jerarquia
LEFT JOIN PERSONA PERSONA_JEFE ON JAPR_FK_PER_ID_JEFE = PERSONA_JEFE.PER_ID
LEFT JOIN COLECTIVO COL ON COL.COL_ID = PERSONA.PER_FK_COLECTIVO_ID
WHERE PERSONA.PER_FK_EMPRESA_ID = 413 --Id de empresa
AND (RHF_FECHA_HORA_INICIO >= CONVERT(DATETIME,'2020-06-01 00:00:00.000',101) AND RHF_FECHA_HORA_INICIO <= CONVERT(DATETIME,'2021-04-19 00:00:00.000',101))
--and year(RHF_FECHA_HORA_INICIO)=FILTER_ANO and (FILTER_MES = 0 or MONTH(RHF_FECHA_HORA_INICIO)=FILTER_MES)
and year(RHF_FECHA_HORA_INICIO)=2021 and (4 = 0 or MONTH(RHF_FECHA_HORA_INICIO)=4)
ORDER BY RHF_FECHA_HORA_INICIO DESC