--SELECT USUARIOS ADMINISTRADORES

USE [LocalFlex]
GO

SELECT [PER_ID]
      ,[PER_NIF]
      ,[PER_USUARIO_REAL]
	  ,ISNULL(PER_USUARIO_ADMINISTRADOR, 1) AS ADMINISTRADOR
      ,[PER_BAJA_SISTEMA]
      ,[PER_NOMBRE]
     
  FROM [dbo].[PERSONA]
  
  WHERE PER_FK_EMPRESA_ID = 13169 

  ORDER BY PER_USUARIO_ADMINISTRADOR
GO


