--SELECT VACACIONES PLAN

SELECT 

SELECT *
FROM VACACIONES_PLAN
WHERE
VAP_FK_EMPRESA_ID = 190


SELECT 
VAP_ID, 
ISNULL(VAP_VER_VACACIONES_SUPERIOR_COMPAÑERO,0) AS VAP_VER_VACACIONES_SUPERIOR_COMPAÑERO 
FROM VACACIONES_PLAN  
WHERE VAP_ID = 90