--GET PETICION PROCESOS VOLVEMOS/PARKING/RESTAURANTE
SELECT
PRE_ID AS 'PeticionReservaId'
, ISNULL(PRE_FECHA, ADH_FECHA_PETICION) AS 'FechaSolicitada'
, PER_NIF AS 'PerNif'
, PER_NOMBRE AS 'PersonaNombre'
, PER_APELLIDOS AS 'PersonaApellidos'
, PER_FK_CENTRO_TRABAJO_ID AS 'CentroTrabajoId'
, PPR_ID AS 'ProcesoId'
, ADH_ESTADO AS 'ReservaEstado'
FROM ADHESION_GENERICO
INNER JOIN PERSONA_PLAN
	ON PPL_ID = ADH_PPL_ID
INNER JOIN EMPRESA_PLAN
	ON PLA_ID = PPL_FK_EMPRESA_PLAN_ID
INNER JOIN PERSONA
	ON PER_ID = PPL_FK_PERSONA_ID
INNER JOIN OFERTA_ITEM
	ON OFE_ID = ADH_FK_OFERTA_ITEM_ID
	LEFT JOIN PETICION_RESERVA
	ON PRE_FK_ADHESION_GENERICO_ID = ADH_ID
LEFT JOIN PETICION_TURNO_FECHAS
	ON PTF_ID = PRE_FK_PETICION_TURNO_FECHAS_ID 
LEFT JOIN PETICION_CAPACIDADES
	ON PCA_ID = PTF_FK_PETICION_CAPACIDADES_ID
INNER JOIN PETICION_PROCESO
	ON PCA_FK_PETICION_PROCESO_ID = PPR_ID
LEFT JOIN RAZON_SOCIAL
	ON RAZ_ID = PER_FK_RAZON_SOCIAL_ID
LEFT JOIN CENTRO_TRABAJO
	ON CTR_ID = ISNULL(PCA_FK_CENTRO_TRABAJO_ID, PER_FK_CENTRO_TRABAJO_ID)
 WHERE 0 = 0 
 AND  PPR_ID = 3
 AND ADH_ESTADO = 2
 AND CONVERT(DATE, ISNULL(PRE_FECHA, ADH_FECHA_PETICION)) = CONVERT(DATE, '2022-05-04')