SELECT DISTINCT
PCU_DESC As 'UnidadDescripcionId'
,PCU_DESC As 'UnidadDescripcion'
FROM PETICION_PROCESO
INNER JOIN PETICION_CAPACIDADES
    ON PPR_ID = PCA_FK_PETICION_PROCESO_ID
INNER JOIN PETICION_CAPACIDADES_UNIDADES
    ON PCU_FK_PETICION_CAPACIDAD_ID = PCA_ID
INNER JOIN PETICION_TIPO_PROCESO
    ON PPR_FK_PETICION_TIPO_PROCESO = PTP_ID
WHERE
PPR_FK_EMPRESA_ID = 38
AND PPR_FK_PETICION_TIPO_PROCESO IS NULL OR PPR_FK_PETICION_TIPO_PROCESO = 1


SELECT DISTINCT
PCU_DESC As 'UnidadDescripcionId'
,PCU_DESC As 'UnidadDescripcion'
FROM PETICION_PROCESO
INNER JOIN PETICION_CAPACIDADES
    ON PPR_ID = PCA_FK_PETICION_PROCESO_ID
INNER JOIN PETICION_CAPACIDADES_UNIDADES
    ON PCU_FK_PETICION_CAPACIDAD_ID = PCA_ID
INNER JOIN PETICION_TIPO_PROCESO
    ON PPR_FK_PETICION_TIPO_PROCESO = PTP_ID
WHERE
PPR_FK_EMPRESA_ID = 632
AND PPR_FK_PETICION_TIPO_PROCESO = 3


SELECT 
PCU_DESC As 'UnidadDescripcionId'
,PCU_DESC As 'UnidadDescripcion'
FROM PETICION_PROCESO
INNER JOIN PETICION_CAPACIDADES
    ON PPR_ID = PCA_FK_PETICION_PROCESO_ID
INNER JOIN PETICION_CAPACIDADES_UNIDADES
    ON PCU_FK_PETICION_CAPACIDAD_ID = PCA_ID
INNER JOIN PETICION_TIPO_PROCESO
    ON PPR_FK_PETICION_TIPO_PROCESO = PTP_ID

 WHERE 0 = 0 
 AND PPR_FK_EMPRESA_ID = 632
 AND (PPR_FK_PETICION_TIPO_PROCESO IS NULL OR PPR_FK_PETICION_TIPO_PROCESO = 1)
 ORDER BY UnidadDescripcionId




