-- Update PRE- PARTE_MEDICO_CONTINGENCIA_CAMPOS by COD_INTERFACE
BEGIN TRANSACTION

UPDATE PRESuez.dbo.PARTE_MEDICO_CONTINGENCIA_CAMPOS
SET PMCC_TIPO_CAMPO = 2
WHERE PMCC_COD_INTERFACE = 'DuracionProceso'

ROLLBACK
COMMIT