--DELETE ACEPTO POLITICA TO ALL USERS FROM EMPRESA X 
BEGIN TRANSACTION

UPDATE LocalRegHorario.dbo.RH_PERSONA 
SET RHP_ACEPTO_CONDICIONES = NULL
WHERE RHP_ID IN(
	SELECT RHP_ID FROM
	localFlex.dbo.PERSONA
	INNER JOIN LocalRegHorario.dbo.RH_PERSONA
	ON PER_ID = RHP_FK_PERSONA_ID 
	AND RHP_FK_RH_CONEXION_ID = 1
	WHERE PER_FK_EMPRESA_ID = 1728
	AND PER_BAJA_SISTEMA IS NULL)

ROLLBACK
COMMIT


--DELETE ACEPTO POLITICA TO A NIF LIST
BEGIN TRANSACTION

UPDATE RegHorarioPRE.dbo.RH_PERSONA 
SET RHP_ACEPTO_CONDICIONES = NULL
WHERE RHP_ID IN(
	SELECT RHP_ID FROM
	PERSONA
	INNER JOIN RegHorarioPRE.dbo.RH_PERSONA
	ON PER_ID = RHP_FK_PERSONA_ID 
	AND RHP_FK_RH_CONEXION_ID = 1
	WHERE PER_NIF IN ('77133934F', '48093142G', '02744066M', '72504070C', '06010938A', '53822576T'))

ROLLBACK
COMMIT





