--SELECT TODOS LOS FINALIZADOS DEL NIF 299840
SELECT
RHF_ID
,PERSONA.PER_NIF AS 'NIF'
, CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,103) AS 'Fecha Registro'
, ISNULL(CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,24),'No informado') AS 'Hora inicio (Finalizado)'
, ISNULL(CONVERT(VARCHAR,RHF_FECHA_HORA_FIN,24),'No informado') AS 'Hora fin (Finalizado)'
,   [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHF_TIEMPO_EFECTIVO, 's')  AS 'Tiempo efectivo (Finalizado)'
,   [LocalRegHorario].[dbo].ConvertTiempoEnHHMMSS(RHF_TIEMPO_PAUSA, 's')  AS 'Tiempo de pausa (Finalizado)'
FROM [LocalRegHorario].[dbo].[RH_PERSONA]
INNER JOIN LocalFlex.dbo.PERSONA ON PER_ID = RHP_FK_PERSONA_ID
INNER JOIN [LocalRegHorario].[dbo].[RH_FINALIZADOS] ON RHF_FK_RH_PERSONA_ID = RHP_ID
WHERE PER_NIF = '20631'
AND RHP_FK_RH_CONEXION_ID = 1
ORDER BY RHF_FECHA_HORA_INICIO DESC


SELECT
RHF_ID
,RHP_ID
,PER_ID
,PERSONA.PER_NIF AS 'NIF'
, CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,103) AS 'Fecha Registro'
, ISNULL(CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,24),'No informado') AS 'Hora inicio (Finalizado)'
, ISNULL(CONVERT(VARCHAR,RHF_FECHA_HORA_FIN,24),'No informado') AS 'Hora fin (Finalizado)'
FROM [LocalRegHorario].[dbo].[RH_PERSONA]
INNER JOIN LocalFlex.dbo.PERSONA ON PER_ID = RHP_FK_PERSONA_ID
INNER JOIN [LocalRegHorario].[dbo].[RH_FINALIZADOS] ON RHF_FK_RH_PERSONA_ID = RHP_ID
WHERE PER_NIF = '845469' --Nif para PRO = 11839273T 
AND RHP_FK_RH_CONEXION_ID = 1
AND CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,103) = '25/08/2021'


SELECT *
FROM RH_FINALIZADOS
WHERE RHF_FK_RH_PERSONA_ID = 132409 --ID
AND CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,103) = '25/08/2021'


BEGIN TRAN
	DELETE  RH_FINALIZADOS
	WHERE	RHF_ID = 4449906
ROLLBACK
COMMIT


BEGIN TRAN
DELETE RH_FINALIZADOS
	WHERE RHF_FK_RH_PERSONA_ID = 132409
	AND CONVERT(VARCHAR,RHF_FECHA_HORA_INICIO,103) = '25/08/2021'
ROLLBACK
COMMIT