

--SELECT PERSONA ID FROM PPL_ID
SELECT PPL_FK_PERSONA_ID
FROM localFlex.dbo.PERSONA_PLAN
WHERE PPL_ID = 3055277   --PER_ID = 158949

--SELECT RHP_ID FROM PER_ID
SELECT * 
FROM LocalRegHorario.dbo.RH_PERSONA RHP
WHERE RHP.RHP_FK_PERSONA_ID = 158949  --RHP_ID = 120909

--SELECT TOP 100 REGISTROS FROM RHP_ID
SELECT TOP 100 * 
FROM LocalRegHorario.dbo.RH_REGISTROS
WHERE RHG_FK_RH_PERSONA_ID = 120909
ORDER BY RHG_FECHA_HORA DESC

--SELECT TOP 100 FINALIZADOS FROM RHP_ID
SELECT TOP 100 * 
FROM LocalRegHorario.dbo.RH_FINALIZADOS
WHERE RHF_FK_RH_PERSONA_ID = 64659
ORDER BY RHF_FECHA_HORA_INICIO DESC

SELECT * 
FROM LocalRegHorario.dbo.RH_FINALIZADOS
WHERE RHF_MOTIVO_REGULARIZACION = 'Regularización a 0 Autogenerado'
ORDER BY RHF_FECHA_HORA_INICIO ASC




