--SELECT TOP 50 LOG ERRORS FROM ALL
SELECT TOP 50 *
FROM LOG_ERROR
ORDER BY ERR_FECHA DESC


--SELECT TOP 50 LOG ERRORS FROM MY PC
SELECT TOP 50 *
FROM LOG_ERROR
WHERE ERR_PATH LIKE '%C:\Source\Repos\Platform10\src%'
ORDER BY ERR_FECHA DESC


