SELECT 
 RV_OI_ID 
,[RV_OI_EMPLEADO_ID]
,[RV_OI_VALOR_OBJETIVO]
,[RV_OI_VALOR_OBTENIDO_KR]
,
CASE
WHEN RV_OI_VALOR_OBJETIVO = RV_OI_VALOR_OBTENIDO_KR THEN 100
WHEN RV_OI_VALOR_OBJETIVO = 0 AND RV_OI_VALOR_OBTENIDO_KR <> 0 THEN CONVERT(INT,RV_OI_VALOR_OBTENIDO_KR) --Aclarar bien esta posible casuística.
WHEN RV_OI_VALOR_OBJETIVO != 0 AND RV_OI_VALOR_OBTENIDO_KR = 0 THEN '0' 
ELSE CONVERT(INT, RV_OI_VALOR_OBTENIDO_KR * 100 / RV_OI_VALOR_OBJETIVO)
END AS '% CONSECUCION'
FROM [LocalFlex].[dbo].[RV_OBJETIVO_INTEGRACION]


