SELECT
CSV.ID 'Id',
FECHA_CREACION 'FechaHora',
PER_ID 'PersonaId',
PER_NIF 'Nif',
PER_NOMBRE 'Nombre', 
PER_APELLIDOS 'Apellidos',
CASE WHEN (CRM_DIA_VACACIONES.SOLICITUD_ANULACION = 1 AND NOT ESTADO = 5 AND NOT ESTADO = 2) THEN 'Pendiente Anulacion' WHEN ESTADO = 1 THEN 'Aceptado' WHEN ESTADO = 2 THEN 'Denegado' WHEN (ESTADO = 4 OR ESTADO = 3) THEN 'Pendiente' WHEN ESTADO = 5 THEN 'Anulada Aceptada' Else '' END 'Estado',
CASE WHEN (CRM_DIA_VACACIONES.SOLICITUD_ANULACION = 1 AND NOT ESTADO = 5 AND NOT ESTADO = 2) THEN 'Anulacion Vacaciones' WHEN TIPO_SOLICITUD = 0 THEN 'Vacaciones' WHEN TIPO_SOLICITUD = 1 THEN 'Intensivas' ELSE 'Horas' END  As 'TipoSolicitud',
CASE WHEN (CRM_DIA_VACACIONES.SOLICITUD_ANULACION = 1 AND NOT ESTADO = 5 AND NOT ESTADO = 2) THEN 'Anulacion Vacaciones' ELSE 'Vacaciones' END As TipoSolicitudInterna,
'' As 'Descripcion',
'' As 'Motivo',
'' As 'FechaDiaRegistro',
(STUFF((SELECT CAST('; ' + CONVERT(VARCHAR, FORMAT(CAST([FECHA] As Date),  'dd/MM/yyyy'), 120) As VARCHAR(MAX))
	FROM CRM_DIA_VACACIONES
	WHERE FK_SOLICITUD = CSV.ID
	FOR XML PATH ('')), 1, 2, '')) As 'DiasSolicitados',
'' As 'AusFechaInicio',
'' As 'AusFechaFin'
FROM CRM_SOLICITUD_VACACIONES CSV
INNER JOIN CRM_DIA_VACACIONES
ON CSV.ID = FK_SOLICITUD
INNER JOIN VACACIONES_PLAN
ON VAP_ID = CRM_DIA_VACACIONES.FK_VACACIONES_PLAN_ID
INNER JOIN PERSONA
ON CSV.FK_PERSONA = PER_ID
INNER JOIN JERARQUIA_APROBACION_PRODUCTOS_RELACION
ON JAPR_FK_PER_ID_COLABORADOR = PER_ID



