
SELECT * 
FROM RH_CONEXION

SELECT * 
FROM LocalFlex.dbo.PERSONA_PLAN
WHERE PPL_ID = 3022040

SELECT * FROM RH_PERSONA
WHERE RHP_FK_PERSONA_ID = 845469
AND RHP_FK_RH_CONEXION_ID = 1
--RHP_ID = 132409

SELECT *
FROM RH_FINALIZADOS
WHERE RHF_FK_RH_PERSONA_ID = 132409 -- ESTO AQUI ES EL RH_PERSONA:: RHP_ID
ORDER BY RHF_FECHA_HORA_INICIO DESC
--RHF_ID =


SELECT *
FROM RH_REGISTROS
WHERE RHG_FK_RH_PERSONA_ID = 132409
ORDER BY RHG_FECHA_HORA DESC
