SELECT TOP (1000) [RHF_ID]
      ,[RHF_FK_RH_PERSONA_ID]
      ,[RHF_TIEMPO_EFECTIVO]
      ,[RHF_TIEMPO_PAUSA]
      ,[RHF_FECHA_HORA_INICIO]
      ,[RHF_FECHA_HORA_FIN]
      ,[RHF_ESTADO]
      ,[RHF_ESTADO_TEXTO]
      ,[RHF_MOTIVO_REGULARIZACION]
      ,[RHF_MODIFICADO]
      ,[RHF_REGISTRO_MANUAL]
      ,[RHF_TIEMPO_EXTRA_GENERADO]
      ,[RHF_REGISTRO_PROCESO_AUTOMATICO]
      ,[RHF_FECHA_REGISTRO_PROCESO_AUTOMATICO]
      ,[RHF_MOTIVO_NUEVO]
      ,[RHF_TIPO_FECHA_FIN_AUTOMATICO]
      ,[RHF_MOTIVO_HORAS_EXTRA]
      ,[RHF_TIEMPO_EXTRA_AÑADIDO]
      ,[RHF_TIEMPO_EFECTIVO_MANUAL]
  FROM [LocalRegHorario].[dbo].[RH_FINALIZADOS]
  WHERE RHF_FK_RH_PERSONA_ID = 133193

  SELECT * FROM RH_REGISTROS 
  WHERE RHG_FK_RH_PERSONA_ID = 133193

  BEGIN TRAN
	DELETE  RH_REGISTROS
	WHERE	RHG_ID = 5686048
  ROLLBACK
  COMMIT

  BEGIN TRAN
  UPDATE RH_FINALIZADOS
	SET RHF_ESTADO_TEXTO = NULL 
	WHERE RHF_ID = 3718871;
  ROLLBACK
  COMMIT

