SELECT *
FROM LocalFlex.dbo.PERSONA_PLAN
WHERE PPL_ID = 3077709

--SELECT ID, HORA INICIO Y HORA FIN
SELECT 
RHF.RHF_ID,
RHF_FECHA_HORA_INICIO, 
RHF_FECHA_HORA_FIN 
FROM
localFlex.dbo.PERSONA
	INNER JOIN LocalRegHorario.dbo.RH_PERSONA
	ON PER_ID = RHP_FK_PERSONA_ID 
	AND RHP_FK_RH_CONEXION_ID = 1
	INNER JOIN LocalRegHorario.dbo.RH_FINALIZADOS RHF
	ON RHP_ID = RHF_FK_RH_PERSONA_ID
WHERE PER_ID IN ('145561')
ORDER BY RHF_FECHA_HORA_INICIO DESC


--SELECT ALL REGISTRES FROM PERSONA ID
SELECT *
FROM LocalRegHorario.dbo.RH_REGISTROS
WHERE RHG_FK_RH_PERSONA_ID = 92968
ORDER  BY RHG_FECHA_HORA DESC


--DELETE FINALIZADOS
BEGIN TRANSACTION

DELETE FROM LocalRegHorario.dbo.RH_FINALIZADOS
WHERE RHF_ID IN ('5572203') 

DELETE FROM LocalRegHorario.dbo.RH_REGISTROS
WHERE RHG_ID IN ('8541718','8541719')

ROLLBACK
COMMIT

