
--SELECT FECHA ACEPTACION RGPD
USE [LocalFlex]
GO

SELECT [PER_ID]
      ,[PER_NIF]
      ,[PER_NOMBRE]
      ,[PER_APELLIDOS]
	  ,[PER_FECHA_ACEPTACION_RGPD]

   FROM [dbo].[PERSONA]
   WHERE [PER_FECHA_ACEPTACION_RGPD] IS NOT NULL 
   AND PER_FK_EMPRESA_ID = 1728 --THALES

GO




