/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [RHF_ID]
      ,[RHF_FK_RH_PERSONA_ID]
      ,[RHF_TIEMPO_EFECTIVO]
      ,[RHF_TIEMPO_PAUSA]
      ,[RHF_FECHA_HORA_INICIO]
      ,[RHF_FECHA_HORA_FIN]
      ,[RHF_ESTADO]
      ,[RHF_ESTADO_TEXTO]
      ,[RHF_MOTIVO_REGULARIZACION]
      ,[RHF_MODIFICADO]
      ,[RHF_REGISTRO_MANUAL]
      ,[RHF_TIEMPO_EXTRA_GENERADO]
      ,[RHF_REGISTRO_PROCESO_AUTOMATICO]
      ,[RHF_FECHA_REGISTRO_PROCESO_AUTOMATICO]
      ,[RHF_MOTIVO_NUEVO]
      ,[RHF_TIPO_FECHA_FIN_AUTOMATICO]
      ,[RHF_MOTIVO_HORAS_EXTRA]
      ,[RHF_TIEMPO_EXTRA_AÑADIDO]
      ,[RHF_TIEMPO_EFECTIVO_MANUAL]
  FROM [LocalRegHorario].[dbo].[RH_FINALIZADOS]
  WHERE RHF_FK_RH_PERSONA_ID = 120094

  SELECT * FROM RH_REGISTROS 
  WHERE RHG_FK_RH_PERSONA_ID = 64831
  ORDER BY RHG_FECHA_HORA

  SELECT *
  FROM RH_FINALIZADOS
  WHERE RHF_FK_RH_PERSONA_ID = 64831
  ORDER BY RHF_FECHA_HORA_INICIO

  BEGIN TRAN
	DELETE  RH_REGISTROS
	WHERE	RHG_ID IN ( 10492718, 10492719)
  ROLLBACK
  COMMIT

  BEGIN TRAN
    DELETE  RH_FINALIZADOS
	WHERE RHF_ID = 6999131
  ROLLBACK
  COMMIT

 BEGIN TRAN
  UPDATE RH_FINALIZADOS
	SET  RHF_FECHA_HORA_INICIO = 2021-05-23, RHF_FECHA_HORA_FIN = 2021-05-23
	WHERE RHF_ID = 3718858;
  ROLLBACK
  COMMIT