SELECT *
FROM localFlex.dbo.PETICION_PROCESO

SELECT *
FROM LocalSuez.dbo.PETICION_PROCESO

-- ADD CONFIGURATION BIT TO LOCALFLEX AND LOCALSUEZ

BEGIN TRAN

ALTER TABLE [localFlex].[dbo].[PETICION_PROCESO]
ADD PPR_NOTIFICACION_CENTRO_TRABAJO_MISMO_DIA BIT NOT NULL DEFAULT (0)

ALTER TABLE [LocalSuez].[dbo].[PETICION_PROCESO]
ADD PPR_NOTIFICACION_CENTRO_TRABAJO_MISMO_DIA BIT NOT NULL DEFAULT (0)

ROLLBACK
COMMIT

