--USUARIOS CON BOLSA DUPLICADA EN LOCAL
-- PPL-ID: 3017056 / 3017001 / 3016811

--PRUEBA CON PPL-ID: 3016811

--OBTENGO RH_PERSONA_ID Y TODOS LOS REGISTROS QUE CUMPLEN FECHA Y REGULARIZACIÓN
SELECT  RHF_FK_RH_PERSONA_ID, RHF_ID 
FROM LocalRegHorario.dbo.RH_FINALIZADOS
WHERE RHF_FK_RH_PERSONA_ID IN (
	SELECT RHP_ID
	FROM LocalRegHorario.dbo.RH_PERSONA
	WHERE RHP_FK_PERSONA_ID IN (
		SELECT PPL_FK_PERSONA_ID
		FROM localFlex.dbo.PERSONA_PLAN
		WHERE PPL_ID = 3016811 )
	AND RHP_FK_RH_CONEXION_ID = 1)
	AND RHF_MOTIVO_REGULARIZACION = 'Regularización a 0'
	AND RHF_FECHA_HORA_INICIO = '2022-11-01'
	ORDER BY RHF_ID


--OPCIÓN A BORRO TODOS LOS REGISTROS QUE PONGA EN EL IN
BEGIN TRANSACTION 

DELETE FROM 
LocalRegHorario.dbo.RH_FINALIZADOS
WHERE RHF_ID IN (5582224, 5582225, 5582226, 5582227)

ROLLBACK
COMMIT


--OPCION B BORRO TODOS LOS REGISTROS MENOS EL PRIMERO
BEGIN TRANSACTION

DELETE 
FROM LocalRegHorario.dbo.RH_FINALIZADOS
WHERE  RHF_FK_RH_PERSONA_ID = 64903
AND RHF_MOTIVO_REGULARIZACION = 'Regularización a 0'
AND RHF_FECHA_HORA_INICIO = '2022-11-01'
AND RHF_ID > (
	SELECT MIN(RHF_ID)
	FROM LocalRegHorario.dbo.RH_FINALIZADOS
	WHERE RHF_FK_RH_PERSONA_ID = 64903
	AND RHF_MOTIVO_REGULARIZACION = 'Regularización a 0'
	AND RHF_FECHA_HORA_INICIO = '2022-11-01'
)	

ROLLBACK
COMMIT