SELECT 
       PER_FK_EMPRESA_ID
	  ,EMP_NOMBRE
	  ,PER_NIF
	  ,PER_NOMBRE 
      ,PER_APELLIDOS
	  ,PER_NUMERO_EMPLEADO 
      ,PER_USUARIO_REAL
	  ,PER_FK_PAIS_ASIGNACION

FROM PlataformaPRE.[dbo].[PERSONA]
  INNER JOIN EMPRESA ON PER_FK_EMPRESA_ID = EMP_ID
WHERE PER_FK_PAIS_ASIGNACION IS NULL 
  AND PER_BAJA_SISTEMA IS NULL
ORDER BY EMP_NOMBRE