SELECT COUNT(*) FROM (
SELECT   NOP_FECHA,   NOP_ID,   NOP_TIPO,   NOP_FILE_NAME,   PER_NOMBRE,   PER_APELLIDOS,   PER_NIF,   PER_NUMERO_EMPLEADO,   EDP_NOMBRE,   RAZ_NOMBRE,   CTR_NOMBRE,   PER_ID,   
ISNULL(NOP_ESTADO, 0) AS NOP_ESTADO,   ROW_NUMBER() OVER(ORDER BY NOP_FECHA DESC, PER_APELLIDOS, PER_NOMBRE DESC) as ROW_NUM  FROM  NOMINA_PERSONA 
INNER JOIN   PERSONA ON NOMINA_PERSONA.NOP_FK_PERSONA_ID = PERSONA.PER_ID 
LEFT OUTER JOIN   EMPRESA_DEPARTAMENTO ON PERSONA.PER_FK_DEPARTAMENTO = EMPRESA_DEPARTAMENTO.EDP_ID 
INNER JOIN   RAZON_SOCIAL ON PERSONA.PER_FK_RAZON_SOCIAL_ID = RAZON_SOCIAL.RAZ_ID 
LEFT OUTER JOIN   CENTRO_TRABAJO ON PERSONA.PER_FK_CENTRO_TRABAJO_ID = CENTRO_TRABAJO.CTR_ID 
WHERE   PER_FK_EMPRESA_ID=13169 AND PER_FK_PAIS_ASIGNACION = 73) kk


SELECT * FROM   (
SELECT   NOP_FECHA,   NOP_ID,   NOP_TIPO,   NOP_FILE_NAME,   PER_NOMBRE,   PER_APELLIDOS,   PER_NIF,   PER_NUMERO_EMPLEADO,   EDP_NOMBRE,   RAZ_NOMBRE,   CTR_NOMBRE,   PER_ID,  
ISNULL(NOP_ESTADO, 0) AS NOP_ESTADO,   ROW_NUMBER() OVER(ORDER BY NOP_FECHA DESC, PER_APELLIDOS, PER_NOMBRE DESC) as ROW_NUM  FROM   NOMINA_PERSONA 
INNER JOIN   PERSONA ON NOMINA_PERSONA.NOP_FK_PERSONA_ID = PERSONA.PER_ID 
LEFT OUTER JOIN   EMPRESA_DEPARTAMENTO ON PERSONA.PER_FK_DEPARTAMENTO = EMPRESA_DEPARTAMENTO.EDP_ID 
INNER JOIN   RAZON_SOCIAL ON PERSONA.PER_FK_RAZON_SOCIAL_ID = RAZON_SOCIAL.RAZ_ID 
LEFT OUTER JOIN   CENTRO_TRABAJO ON PERSONA.PER_FK_CENTRO_TRABAJO_ID = CENTRO_TRABAJO.CTR_ID 
WHERE   PER_FK_EMPRESA_ID=13169 AND PER_FK_PAIS_ASIGNACION = 73) kk  
WHERE 0 <= ROW_NUM AND ROW_NUM <= 499 
AND PER_NIF = '39395197S'
--AND PER_NIF = '39501796D'
--AND PER_NOMBRE = 'Julia'


SELECT   * FROM   (
SELECT   NOP_FECHA,   NOP_ID,   NOP_TIPO,   NOP_FILE_NAME,   PER_NOMBRE,   PER_APELLIDOS,   PER_NIF,   PER_NUMERO_EMPLEADO, EDP_NOMBRE,   RAZ_NOMBRE,   CTR_NOMBRE, PER_ID,  
ISNULL(NOP_ESTADO, 0) AS NOP_ESTADO,   ROW_NUMBER() OVER(ORDER BY NOP_FECHA DESC, PER_APELLIDOS, PER_NOMBRE DESC) as ROW_NUM  FROM   NOMINA_PERSONA 
INNER JOIN   PERSONA ON NOMINA_PERSONA.NOP_FK_PERSONA_ID = PERSONA.PER_ID 
LEFT OUTER JOIN   EMPRESA_DEPARTAMENTO ON PERSONA.PER_FK_DEPARTAMENTO = EMPRESA_DEPARTAMENTO.EDP_ID 
INNER JOIN   RAZON_SOCIAL ON PERSONA.PER_FK_RAZON_SOCIAL_ID = RAZON_SOCIAL.RAZ_ID 
LEFT OUTER JOIN   CENTRO_TRABAJO ON PERSONA.PER_FK_CENTRO_TRABAJO_ID = CENTRO_TRABAJO.CTR_ID 
WHERE   PER_FK_EMPRESA_ID=13169 AND PER_NOMBRE = 'Julia' and PER_FK_PAIS_ASIGNACION = 73) kk