

--IDENTIFICAR TABLA A PARTIR DEL NOMBRE DE UNA COLUMNA

SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE '%DEPARTAMENTO'
ORDER BY TABLE_NAME


SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME in ('%DEPARTAMENTO%')

--OBTENER TODA LA DEFINICION DE UNA COLUMNA
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'EMPRESA_DEPARTAMENTO'
AND COLUMN_NAME = 'FK_EMPRESA_EMP_ID'


SELECT  COLUMN_NAME, DATA_TYPE,COLUMN_DEFAULT,IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'GRUPO_APARIENCIA '
AND COLUMN_NAME = 'GAP_FORZAR_FIRMA_CAMBIO_SDAD'